# Generated by Django 3.1.7 on 2021-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ide',
            field=models.IntegerField(default=0),
        ),
    ]
