# Generated by Django 3.1.7 on 2021-03-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeeditor', '0002_todo_ide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
